/*
 * File: app/view/TaskView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchCRUD.view.TaskView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.taskview',

    requires: [
        'TouchCRUD.view.TaskList',
        'Ext.navigation.Bar',
        'Ext.Button',
        'Ext.dataview.List'
    ],

    config: {
        itemId: 'mainView',
        navigationBar: {
            docked: 'top',
            itemId: 'navBar',
            items: [
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: 'addButton',
                    iconCls: 'add'
                },
                {
                    xtype: 'button',
                    align: 'right',
                    hidden: true,
                    itemId: 'editButton',
                    iconCls: 'compose'
                },
                {
                    xtype: 'button',
                    align: 'right',
                    hidden: true,
                    itemId: 'removeButton',
                    iconCls: 'delete'
                }
            ]
        },
        items: [
            {
                xtype: 'tasklist'
            }
        ]
    }

});