/*
 * File: app/view/TaskView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchCRUD.view.TaskView', {
    extend: 'Ext.Panel',
    alias: 'widget.taskview',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.field.Toggle'
    ],

    config: {
        layout: {
            type: 'card',
            animation: 'slide'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'backButton',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'addButton',
                        iconCls: 'add'
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        itemId: 'editButton',
                        iconCls: 'compose'
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        itemId: 'removeButton',
                        iconCls: 'delete'
                    }
                ]
            },
            {
                xtype: 'list',
                title: 'Task List',
                itemId: 'list',
                autoDestroy: false,
                itemTpl: [
                    '<div>',
                    '    <tpl if="completed">COMPLETED:</tpl>',
                    '    {priority} -',
                    '    {description}',
                    '    <tpl if="dueDate"> - {dueDate:date}</tpl>',
                    '</div>'
                ],
                store: 'Tasks'
            },
            {
                xtype: 'panel',
                itemId: 'details',
                padding: 10,
                tpl: [
                    '<p><label>Description: </label><span>{description}</span></p>'
                ],
                autoDestroy: false
            },
            {
                xtype: 'formpanel',
                itemId: 'form',
                autoDestroy: false,
                items: [
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Description',
                                labelWidth: '35%',
                                name: 'description'
                            },
                            {
                                xtype: 'selectfield',
                                label: 'Priority',
                                labelWidth: '35%',
                                name: 'priority',
                                required: true,
                                options: [
                                    {
                                        text: 'Normal',
                                        value: 'Normal'
                                    },
                                    {
                                        text: 'High',
                                        value: 'High'
                                    },
                                    {
                                        text: 'Low',
                                        value: 'Low'
                                    }
                                ],
                                usePicker: true
                            },
                            {
                                xtype: 'datepickerfield',
                                label: 'Due Date',
                                labelWidth: '35%',
                                name: 'dueDate'
                            },
                            {
                                xtype: 'togglefield',
                                label: 'Completed',
                                labelWidth: '35%',
                                name: 'completed'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        itemId: 'saveButton',
                        margin: 10,
                        ui: 'action',
                        text: 'Save'
                    }
                ]
            }
        ]
    }

});