/*
 * File: app/view/TaskDetails.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchCRUD.view.TaskDetails', {
    extend: 'Ext.Panel',
    alias: 'widget.taskdetails',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'taskDetails',
        padding: 10,
        tpl: [
            '<p><label>Description: </label><span>{description}</span></p>'
        ]
    }

});